### ISSUE TITLE
Heroku

### ISSUE THREAD

**Issue by patrickkenney** [patrickkenney/Restaurant#8]
Unable to load app effectively.

**Comment by statik** [comment]
Fixed. The root cause turned out to be that the haml gem was listed in the assets bundler group, which means it was not loaded into the runtime environment on production, which mean the view machinery could not find the haml engine. Moving haml and related gems out of the assets group enabled the production rails config to correctly match .haml files to the haml view engine. Deployed to heroku and confirmed it is working now.

**Comment by patrickkenney** [comment]
Awesome! I love that not only are you fixing things but teaching me as well.
—
